#include "esphome/core/log.h"
#include "opnpool.h"

// #include <driver/gpio.h>

namespace esphome {
namespace opnpool {

static const char *const TAG = "OPNpool";

OPNpool::OPNpool(InternalGPIOPin *rs485_rx_pin, InternalGPIOPin *rs485_tx_pin, InternalGPIOPin *rs485_rts_pin,
                 int rs485_timeout, int dbglvl_datalink, int dbglvl_network, int dbglvl_poolstate,
                 int dbglvl_pooltask, int dbglvl_mqtttask, int dbglvl_hasstask, int dbglvl_httpd, int dbglvl_ipc)
{
  this->RS485_RX_ = rs485_rx_pin;
  this->RS485_TX_ = rs485_tx_pin;
  this->RS485_RTS_ = rs485_rts_pin;
  this->RS485_TIMEOUT_ = rs485_timeout;
  this->DBGLVL_DATALINK_ = dbglvl_datalink;
  this->DBGLVL_NETWORK_ = dbglvl_network;
  this->DBGLVL_POOLSTATE_ = dbglvl_poolstate;
  this->DBGLVL_POOLTASK_ = dbglvl_pooltask;
  this->DBGLVL_MQTTTASK_ = dbglvl_mqtttask;
  this->DBGLVL_HASSTASK_ = dbglvl_hasstask;
  this->DBGLVL_HTTPD_ = dbglvl_httpd;
  this->DBGLVL_IPC_ = dbglvl_ipc;

  this->_moduleNumber = 1;
}

/*
void OPNpool::set_bandwidth(float bandwidth) { bandwidth_ = bandwidth; }

void OPNpool::set_frequency(float frequency) { frequency_ = frequency; }
*/

/**
 * special setup() method that will be called once to set up the component
 * at the time the setup() method is called, all the setters generated by the Python codebase have already run and the all fields are set for your class.
 * The setup() method should set up the communication interface for the component and check if communication works (if not, it should call mark_failed()).
 * 
 */ 
void OPNpool::setup()
{
    ESP_LOGI(TAG, "OPNpool initialized.");

    /*
    pinMode(GDO0_->get_pin(), INPUT);
    
    ELECHOUSE_cc1101.addSpiPin(SCK_->get_pin(), MISO_->get_pin(), MOSI_->get_pin(), CSN_->get_pin(), _moduleNumber);
    ELECHOUSE_cc1101.setModul(_moduleNumber);
    ELECHOUSE_cc1101.Init();
    ELECHOUSE_cc1101.setRxBW(bandwidth_);
    ELECHOUSE_cc1101.setMHZ(frequency_);
    ELECHOUSE_cc1101.SetRx();
    */
}

// Components should dump their configuration using ESP_LOGCONFIG at startup in dump_config()
void OPNpool::dump_config()
{
  ESP_LOGCONFIG(TAG, "OPNpool:");
  ESP_LOGCONFIG(TAG, "  RS485::");
  LOG_PIN("    Rx Pin:  ", this->RS485_RX_);
  LOG_PIN("    Tx Pin:  ", this->RS485_TX_);
  LOG_PIN("    RTS Pin: ", this->RS485_RTS_);
  ESP_LOGCONFIG(TAG, "    Timeout: %d ms", this->RS485_TIMEOUT_);
  ESP_LOGCONFIG(TAG, "  Debug Levels:");
  ESP_LOGCONFIG(TAG, "    Datalink:  %d", this->DBGLVL_DATALINK_);
  ESP_LOGCONFIG(TAG, "    Network:   %d", this->DBGLVL_NETWORK_);
  ESP_LOGCONFIG(TAG, "    Poolstate: %d", this->DBGLVL_POOLSTATE_);
  ESP_LOGCONFIG(TAG, "    Pooltask:  %d", this->DBGLVL_POOLTASK_);
  ESP_LOGCONFIG(TAG, "    MQTTtask:  %d", this->DBGLVL_MQTTTASK_);
  ESP_LOGCONFIG(TAG, "    HASStask:  %d", this->DBGLVL_HASSTASK_);
  ESP_LOGCONFIG(TAG, "    HTTPd:     %d", this->DBGLVL_HTTPD_);
  ESP_LOGCONFIG(TAG, "    IPC:       %d", this->DBGLVL_IPC_);
}

}  // namespace opnpool
}  // namespace esphome