# ble-proxy device specific config

substitutions:
  device_name: ble-proxy-7
  room_name: "Apartment"
  friendly_name: "BLE-proxy 7"
  description: "BLE-proxy 7 in apartment"

# ble-proxy generic config

<<: !include ble-proxy-base.yaml