# bt-proxy generic configuration

# based on https://github.com/myhomeiot/esphome-components/blob/main/examples/ble_gateway/esphome.yaml

esphome:
  name: ${device_name}
  comment: ${description}
  friendly_name: ${friendly_name}

esp32:
  variant: ESP32
  board: esp32dev
  framework:
    type: esp-idf

logger:
  baud_rate: 0
  
wifi:
  domain: !secret domain_name
  min_auth_mode: WPA2
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap: # enable fallback ap captive portal in case wifi connection fails
    ssid: "${device_name} Config"
    password: !secret wifi_password
  on_connect:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_disconnect:
    - esp32_ble_tracker.stop_scan:

api: # enable HA native API, https://esphome.io/components/api/#homeassistant-event-action
  encryption:
    key: !secret api_encryption_key 

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time  

web_server:
  port: 80
  include_internal: true

captive_portal:
    
esp32_ble_tracker:
  scan_parameters:
    window: 30ms
    interval: 320ms
    continuous: false

bluetooth_proxy:
  active: true

binary_sensor:
  - platform: status
    name: "Home Assistant"
    id: ink_ha_connected
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      id: device_ip
      icon: mdi:ip-outline
      entity_category: diagnostic
    ssid:
      name: "SSID"
      id: device_ssid
      icon: mdi:wifi-settings
      entity_category: diagnostic
  
sensor:
  - platform: wifi_signal
    id: wifi_signal_strength
    name: "WiFi Signal"
    icon: mdi:wifi
    unit_of_measurement: "dBm"  
    state_class: measurement
    update_interval:  10s
    entity_category: diagnostic

  - platform: template
    id: esp_memory
    name: "Free memory"
    icon: mdi:memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: diagnostic

button:
  - platform: restart
    name: "Restart"
    id: restart_button
    icon: mdi:power-cycle
    entity_category: diagnostic

  - platform: factory_reset
    name: Factory Reset
    id: factory_reset_al
    disabled_by_default: true
    entity_category: diagnostic

