# ble-tracker device specific config

substitutions:
  name: ble-tracker-2
  friendly_name: "BLE Tracker 2"
  description: "Bluetooth Low Energy tracker for triangulating devices"
  update_interval_wifi: "120s"

# ble-tracker generic config

<<: !include ble-tracker-base.yaml
