# bt-proxy generic configuration
#
# If you get "ERROR Running command failed: Failed to connect to ESP32: Wrong boot mode detected (0x13)! The chip needs to be in download mode.",
# then bring GPIO0 down (press BOOT), while the esphome upload starts (and applies RST).
# Then let go. See https://docs.espressif.com/projects/esptool/en/latest/esp32/advanced-topics/boot-mode-selection.html

wifi:
  domain: !secret domain_name
  min_auth_mode: WPA2
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap: # enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${name} Fallback Hotspot"
    password: !secret wifi_password

esphome:
  name: ${name}
  comment: ${description}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  
api:
  encryption:
    key: !secret api_encryption_key 

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time  

web_server:
  port: 80
  include_internal: true

captive_portal:
    
bluetooth_proxy:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval:  ${update_interval_wifi}

button:
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      id: device_ip
      icon: "mdi:ip-outline"
      #update_interval: ${update_interval_wifi}
    ssid:
      name: "SSID"
      id: device_ssid
      icon: "mdi:wifi-settings"
      #update_interval:  ${update_interval_wifi}
    #dns_address:
    #  name: "DNS"
    #  id: device_dns
    #  icon: "mdi:dns-outline"
    #  #update_interval: ${update_interval_wifi}
    #bssid:
    #  name: "BSSID"
    #  icon: "mdi:wifi-settings"
    #  update_interval:  ${update_interval_wifi}
    #mac_address:
    #  name: "MAC"
    #  icon: "mdi:network-outline"
    #scan_results:
    #  name: "Wifi Scan"
    #  icon: "mdi:wifi-refresh"
    #  update_interval:  ${update_interval_wifi}
    #  disabled_by_default: true
