# bt-proxy device specific config

substitutions:
  name: bt-proxy-7
  friendly_name: "BT Proxy 7"
  description: "Bluetooth proxy for triangulating devices"
  update_interval_wifi: "120s"

# bt-proxy generic config

<<: !include bt-proxy-base.yaml
