# bt-proxy device specific config

substitutions:
  name: bt-proxy-4
  friendly_name: "BT Proxy 4"
  description: "Bluetooth proxy device for triangulating devices"

# bt-proxy generic config

<<: !include bt-proxy-base.yaml
