# bt-proxy device specific config

substitutions:
  name: bt-proxy-17
  friendly_name: "BT Proxy 17"
  description: "Bluetooth proxy device for triangulating devices"

# bt-proxy generic config

<<: !include bt-proxy-base.yaml
