# bt-proxy generic configuration

wifi:
  domain: .iot.vonkio.com
  min_auth_mode: WPA2
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap: # enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: "${name} Fallback Hotspot"
    password: !secret wifi_password

esphome:
  name: ${name}
  comment: ${description}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  
api:
  encryption:
    key: !secret api_encryption_key 

ota:
  - platform: esphome
    password: !secret ota_password

time:
  - platform: homeassistant
    id: ha_time  

web_server:
  port: 80
  include_internal: true

captive_portal:
    
bluetooth_proxy: