# CircuitSetup Split Single Phase Energy Meter (ATM90E32) with ESP32
# Requires an AC transformer and CT sensors
# https://circuitsetup.us/product/split-single-phase-real-time-whole-house-energy-meter-v1-4/

# Based on https://devices.esphome.io/devices/circuitsetup-split-single-phase-energy-meter-atm90e32-with-esp32/

substitutions:
  name: "electricmeter_dryer"
  friendly_name: "CircuitSetup ATM90E32 Energy Meter"
  comment: "CircuitSetup Split Single Phase Energy Meter with ESP32 and ATM90E32"
  # Interval of how often the power is updated
  update_interval_wifi: "120s"
  update_time_atm90e32: "30s"
  # AC Transformer voltage calibration for the transformer used:
  # - 37106 - 9V AC Transformer, Jameco 157041 (default)
  # - 38302 - 9V AC Transformer, Jameco 112336
  # - 29462 - 12V AC Transformer, Jameco 167151
  # -  3920 - For Meters >= v1.4 rev3 with 9V AC transformer
  voltage_cal: "37106"
  # Current calibration depends for the CT probe used:
  # - 39571 - 80A/26.6mA SCT-010
  # - 25498 - 100A/50mA,SCT-013-000, or may be
  # - 26315 - 100A/50mA, SCT-013
  # - 39473 - 120A/40mA, SCT-016 (default kit CT)
  # - 26315 - 200A/100mA SCT-024: 
  # - 46539 - 100A, Magnalab 
  current_cal: "39473"
  # Line Frequency:
  # - 60 Hz - North America (default)
  # - 50 Hz - Rest of the world
  line_frequency: "60Hz"

esphome:
  name: ${name}
  comment: ${comment}
  friendly_name: ${friendly_name}

# ESP32-D0WDQ6, 4096 kB Flash
esp32:
  variant: esp32
  framework:
    type: esp-idf

wifi:
  domain: !secret domain_name
  min_auth_mode: WPA2
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap: # enable fallback ap captive portal in case wifi connection fails
    ssid: "${name} Config"
    password: !secret wifi_password

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  
api:
  encryption:
    key: !secret api_encryption_key 

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80
  include_internal: true

time:
  - platform: homeassistant
    id: ha_time  

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

button:
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: diagnostic

sensor:
  - platform: atm90e32
    cs_pin: 5
    line_frequency: ${line_frequency}
    gain_pga: 2X
    update_interval: ${update_time_atm90e32}

    phase_a:
      voltage:
        name: "Voltage"
        accuracy_decimals: 0
      #current:
      #  name: "CT1 Current"
      #  id: ct1_current
      #  # The max value for current that the meter can output is 65.535. If you
      #  # expect to measure current over 65A, divide the gain_ct by 2 (120A CT) or
      #  # 4 (200A CT) and multiply the current and power values by 2 or 4 by
      #  # uncommenting the filter below:
      #  #filters:
      #  #  - multiply: 2
      power:
        name: "CT1 Power"
        accuracy_decimals: 0
        id: ct1_power
        #filters:
        #  - multiply: 2
      #reactive_power:
      #  name: "CT1 Reactive Power"
      #  accuracy_decimals: 0
      #  id: ct1_reactive_power
      #  #filters:
      #  #  - multiply: 2
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}

    phase_c:
      #current:
      #  name: "CT2 Current"
      #  id: ct2_current
      #  #filters:
      #  #  - multiply: 2
      power:
        name: "CT2 Power"
        accuracy_decimals: 0
        id: ct2_power
        #filters:
        #  - multiply: 2
      #reactive_power:
      #  name: "CT2 Reactive Power"
      #  accuracy_decimals: 0
      #  id: ct2_reactive_power
      #  #filters:
      #  #  - multiply: 2
      #gain_voltage: ${voltage_cal}
      #gain_ct: ${current_cal}

    #frequency:
    #  name: "Frequency"

    #chip_temperature:
    #  name: "Chip Temp"

    
  #- platform: template
  #  name: "Total Current"
  #  id: ${name}_total_current
  #  lambda: return id(ct1_current).state + id(ct2_current).state;
  #  accuracy_decimals: 2
  #  unit_of_measurement: A
  #  update_interval: ${update_time_atm90e32}
  #  icon: "mdi:current-ac"

  - platform: template
    name: "Total Power"
    id: ${name}_total_power
    lambda: return id(ct1_power).state + id(ct2_power).state;
    accuracy_decimals: 0
    unit_of_measurement: W
    icon: "mdi:power"
    update_interval: ${update_time_atm90e32}

  #- platform: template
  #  name: "Total Reactive Power"
  #  id: ${name}_total_reactive_power
  #  lambda: return id(ct1_reactive_power).state + id(ct2_reactive_power).state;
  #  accuracy_decimals: 0
  #  unit_of_measurement: VAR
  #  icon: "mdi:flash-circle"
  #  update_interval: ${update_time_atm90e32}

  - platform: total_daily_energy
    name: "Total Daily Energy"
    id: ${name}_total_daily_energy
    power_id: ${name}_total_power
    accuracy_decimals: 3
    unit_of_measurement: kWh
    filters:
      - multiply: 0.001

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval:  ${update_interval_wifi}
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      id: device_ip
      icon: "mdi:ip-outline"
      #update_interval: ${update_interval_wifi}
    #dns_address:
    #  name: "DNS"
    #  id: device_dns
    #  icon: "mdi:dns-outline"
    #  #update_interval: ${update_interval_wifi}
    ssid:
      name: "SSID"
      id: device_ssid
      icon: "mdi:wifi-settings"
      #update_interval:  ${update_interval_wifi}
    #bssid:
    #  name: "BSSID"
    #  icon: "mdi:wifi-settings"
    #  update_interval:  ${update_interval_wifi}
    #mac_address:
    #  name: "MAC"
    #  icon: "mdi:network-outline"
    #scan_results:
    #  name: "Wifi Scan"
    #  icon: "mdi:wifi-refresh"
    #  update_interval:  ${update_interval_wifi}
    #  disabled_by_default: true
