# device specific configuration

substitutions:
  devicename: "sonoff-s31-12"
  friendly_devicename: "Sonoff S31 12"
  device_description: "${devicename} - Outlet Switch"
  voltage_cal: "0.5"
  update_interval_wifi: "120s"
  cse7766_throttle_interval: "60s"
  restore_mode_setting: RESTORE_DEFAULT_ON # how the outlet attempts to restore state on bootup
  # RESTORE_DEFAULT_OFF          - Attempt to restore state and default to OFF if not possible to restore.
  # RESTORE_DEFAULT_ON           - Attempt to restore state and default to ON if not possible to restore.
  # RESTORE_INVERTED_DEFAULT_OFF - Attempt to restore state inverted from the previous state and default to OFF.
  # RESTORE_INVERTED_DEFAULT_ON  - Attempt to restore state inverted from the previous state and default to ON.
  # ALWAYS_OFF                   - Always initialize the pin as OFF on bootup.
  # ALWAYS_ON                    - Always initialize the pin as ON on bootup.

# Sonoff S31 generic configuration

<<: !include sonoff-s31-base.yaml
