# Sonoff S20 generic configuration

# based on https://devices.esphome.io/devices/Sonoff-S20/
#
# RESTORE_DEFAULT_OFF          - Attempt to restore state and default to OFF if not possible to restore.
# RESTORE_DEFAULT_ON           - Attempt to restore state and default to ON if not possible to restore.
# RESTORE_INVERTED_DEFAULT_OFF - Attempt to restore state inverted from the previous state and default to OFF.
# RESTORE_INVERTED_DEFAULT_ON  - Attempt to restore state inverted from the previous state and default to ON.
# ALWAYS_OFF                   - Always initialize the pin as OFF on bootup.
# ALWAYS_ON                    - Always initialize the pin as ON on bootup.

# GPIO0	- Push Button (HIGH = off, LOW = on)
# GPIO12 - Relay and its red status LED
# GPIO13 - Green LED (HIGH = off, LOW = on)

wifi:
  domain: !secret domain_name
  min_auth_mode: WPA2
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret wifi_password

esphome:
  name: ${name}
  comment: ${description}
  friendly_name: ${friendly_name}

esp8266:
  board: sonoff_s20

logger:
  baud_rate: 0
  
api:
  encryption:
    key: !secret api_encryption_key 

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80
  include_internal: true

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN
  stop_bits: 1

binary_sensor:
  - platform: gpio
    id: outlet_button
    name:  "Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    entity_category: ''
    on_press:
      - switch.toggle: outlet

  - platform: status
    name: "Connection Status"
    id: connection_status
    entity_category: diagnostic

switch:
  - platform: gpio # outlet output
    id: outlet
    name: 'Outlet'
    pin:
      number: GPIO12
    icon: "mdi:power-socket"
    entity_category: ''
    restore_mode: ${restore_mode_setting}

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval:  ${update_interval_wifi}

button:
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      id: device_ip
      icon: "mdi:ip-outline"
      #update_interval: ${update_interval_wifi}
    ssid:
      name: "SSID"
      id: device_ssid
      icon: "mdi:wifi-settings"
      #update_interval:  ${update_interval_wifi}
    #dns_address:
    #  name: "DNS"
    #  id: device_dns
    #  icon: "mdi:dns-outline"
    #  #update_interval: ${update_interval_wifi}
    #bssid:
    #  name: "BSSID"
    #  icon: "mdi:wifi-settings"
    #  update_interval:  ${update_interval_wifi}
    #mac_address:
    #  name: "MAC"
    #  icon: "mdi:network-outline"
    #scan_results:
    #  name: "Wifi Scan"
    #  icon: "mdi:wifi-refresh"
    #  update_interval:  ${update_interval_wifi}
    #  disabled_by_default: true

##output:
#  - platform: esp8266_pwm # green LED
#    id: green_led
#    pin:
#      number: GPIO13
#      inverted: true
#
##light:
#  - platform: monochromatic
#    name: "Green LED"
#    output: green_led
#    id: green_light
