# device specific config

substitutions:
  name: "sonoff-s31-3"
  friendly_name: "Sonoff-S31 3"
  description: "Socket switch with power monitoring"
  voltage_cal: "0.5"
  update_interval_wifi: "120s"
  cse7766_throttle_interval: "60s"
  restore_mode_setting: RESTORE_DEFAULT_ON # how the outlet attempts to restore state on bootup

# Sonoff S31 generic config

<<: !include sonoff-s31-base.yaml
