# Sonoff S20, device specific config

substitutions:
  name: "sonoff-s20-2"
  friendly_name: "Sonoff-S20 2"
  description: "Socket switch"
  update_interval_wifi: "120s"
  restore_mode_setting: RESTORE_DEFAULT_ON # how the outlet attempts to restore state on bootup

# Sonoff S20, generic config

<<: !include sonoff-s20-base.yaml
